# THIS FILE HAS BEEN AUTOGENERATED BY CS
# DO NOT MODIFY ITS CONTENT. IT WILL BE
# OVERWRITTEN.
#
# CHANGES SHOLUD BE DONE OVER: "./sample.cs.rb"

class Sample

  def hello name
    SC.hello name
  end

  def sum n1, n2
    SC.sum n1, n2
  end

  def rule_of_three a, b, c
    x = SC.multiply c, b
    SC.divide x, a
  end

end
