# THIS FILE HAS BEEN AUTOGENERATED BY CS
# DO NOT MODIFY ITS CONTENT. IT WILL BE
# OVERWRITTEN.

module SC
  
  # id: 48264fe2341b324aa8b9
  #
  # @param [Float] f1
  # @param [Float] f2
  # @return [Float]
  def divide f1, f2
    f1 / f2
  end

  # id: ab234fe2341b324e1224
  #
  # @param [String] s1
  # @return [String] 
  def hello s1
    "Say Hello to #{s1}"
  end

  # id: 234fe23a41b324ea98b7
  #
  # @param [Float] f1
  # @param [Float] f2
  # @return [Float]
  def multiply f1, f2
    f1 + f2
  end

  # id: cd234fe2341b324e98b3
  #
  # @param [Fixnum] n1
  # @param [Fixnum] n2
  # @return [Fixnum]
  def sum n1, n2
    n1 + n2
  end

end
