# THIS FILE HAS BEEN AUTOGENERATED BY CS
# DO NOT MODIFY ITS CONTENT. IT WILL BE
# OVERWRITTEN.

class Sample

  # id: safdh3j43x234zadx
  def hello s1
    "Say Hello to #{s1}"
  end
  
  # id: dasc7dsg7221m3m1d
  def sum i1, i2
    i1 + i2
  end
  
  # id: safg5312km3mk123c
  def rule_of_three f1, f2, f3
    f3 * f2 / f1
  end

end

